package com.vahak.pc.telemetry.service

import com.vahak.pc.telemetry.domain.ApplicationCrash
import com.vahak.pc.telemetry.dto.ApplicationCrashDto
import com.vahak.pc.telemetry.repository.ApplicationCrashRepository
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional

@Service
class ApplicationCrashService(
    private val crashRepository: ApplicationCrashRepository
) {
    private val logger = LoggerFactory.getLogger(ApplicationCrashService::class.java)

    @Transactional
    fun saveCrashLogs(dtos: List<ApplicationCrashDto>) {
        if (dtos.isEmpty()) return

        val entities = dtos.map { dto ->
            ApplicationCrash(
                id = dto.id, // Preserve the ID generated by Android to prevent duplicates
                crashTimestamp = dto.timestamp,
                appVersion = dto.appVersion,
                androidVersion = dto.androidVersion,
                deviceModel = dto.deviceModel,
                exceptionType = dto.exceptionType,
                stackTrace = dto.stackTrace
            )
        }

        crashRepository.saveAll(entities)
        logger.error("🚨 Saved ${entities.size} new crash logs to the database.")
    }
}