server:
  port: 8080

spring:
  application:
    name: pc-telemetry-service

  datasource:
    url: jdbc:postgresql://localhost:5457/pc_telemetry_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:Vahak_Parent_Control_Super_Secure_Key_2026_!@#$$}